import type { HomeFeedSnapshot } from "@/types/site";

export const HOME_PAGE_COPY = {
  titleZh: "秋水CODE花园",
  titleEn: "Qiushui Code Garden",
  primaryActionLabelZh: "查看下载",
  primaryActionLabelEn: "Open Downloads",
  secondaryActionLabelZh: "进入文档",
  secondaryActionLabelEn: "Open Docs",
};

export const CURATED_HOME_FEED_SNAPSHOT: HomeFeedSnapshot = {
  generatedAt: "2026-06-24T00:00:00.000Z",
  news: {
    key: "news",
    titleZh: "AI 资讯",
    titleEn: "AI News",
    updatedAt: "2026-06-24T00:00:00.000Z",
    featuredItem: null,
    items: [
      {
        id: "news-01",
        kind: "NEWS",
        titleZh: "OpenAI 更新模型与平台协同节奏",
        titleEn: "OpenAI updates model and platform cadence",
        summaryZh: "围绕模型能力、接口能力和产品落地节奏的连续更新，适合用来判断近期平台方向。",
        summaryEn: "A recent run of updates around models, APIs, and product rollout signals.",
        sourceName: "OpenAI",
        sourceUrl: "https://openai.com/news/",
        externalUrl: "https://openai.com/news/",
        publishedAt: "2026-06-23T00:00:00.000Z",
        heatScore: 98,
        tags: ["OpenAI", "Platform", "Models"],
      },
      {
        id: "news-02",
        kind: "NEWS",
        titleZh: "Anthropic 持续补强安全与商业化说明",
        titleEn: "Anthropic keeps expanding safety and product notes",
        summaryZh: "信息密度高，适合跟踪安全边界、模型接入方式和商业产品推进。",
        summaryEn: "Useful for following safety boundaries, integration patterns, and product rollout.",
        sourceName: "Anthropic",
        sourceUrl: "https://www.anthropic.com/news",
        externalUrl: "https://www.anthropic.com/news",
        publishedAt: "2026-06-22T00:00:00.000Z",
        heatScore: 95,
        tags: ["Anthropic", "Safety", "Product"],
      },
      {
        id: "news-03",
        kind: "NEWS",
        titleZh: "Google DeepMind 分享研究与系统新进展",
        titleEn: "Google DeepMind shares recent research and system progress",
        summaryZh: "覆盖研究、系统能力和工程侧方向，适合做长期趋势观察。",
        summaryEn: "A broad snapshot across research, systems, and engineering direction.",
        sourceName: "DeepMind",
        sourceUrl: "https://deepmind.google/discover/blog/",
        externalUrl: "https://deepmind.google/discover/blog/",
        publishedAt: "2026-06-21T00:00:00.000Z",
        heatScore: 91,
        tags: ["DeepMind", "Research"],
      },
      {
        id: "news-04",
        kind: "NEWS",
        titleZh: "Google AI Blog 汇总多模态与工具化能力变化",
        titleEn: "Google AI Blog tracks multimodal and tooling changes",
        summaryZh: "多模态应用和工具链层面的变化较多，适合关注工程应用的人快速浏览。",
        summaryEn: "A useful stream for people tracking multimodal product and tooling changes.",
        sourceName: "Google AI",
        sourceUrl: "https://blog.google/technology/ai/",
        externalUrl: "https://blog.google/technology/ai/",
        publishedAt: "2026-06-20T00:00:00.000Z",
        heatScore: 88,
        tags: ["Google", "Multimodal", "Tooling"],
      },
      {
        id: "news-05",
        kind: "NEWS",
        titleZh: "Meta AI 公布开源模型与社区协作动向",
        titleEn: "Meta AI updates open model and community direction",
        summaryZh: "适合观察开源模型策略、社区生态和落地节奏的变化。",
        summaryEn: "A good signal for open-model strategy and community momentum.",
        sourceName: "Meta AI",
        sourceUrl: "https://ai.meta.com/blog/",
        externalUrl: "https://ai.meta.com/blog/",
        publishedAt: "2026-06-18T00:00:00.000Z",
        heatScore: 86,
        tags: ["Meta", "Open Source", "Community"],
      },
      {
        id: "news-06",
        kind: "NEWS",
        titleZh: "微软持续推进 Copilot 与 Agent 生态入口",
        titleEn: "Microsoft keeps expanding Copilot and agent entry points",
        summaryZh: "重点不在单次发布，而在平台接入点越来越多，适合看生态延展。",
        summaryEn: "More notable for ecosystem expansion than any single release event.",
        sourceName: "Microsoft",
        sourceUrl: "https://blogs.microsoft.com/",
        externalUrl: "https://blogs.microsoft.com/",
        publishedAt: "2026-06-17T00:00:00.000Z",
        heatScore: 84,
        tags: ["Microsoft", "Copilot", "Agents"],
      },
      {
        id: "news-07",
        kind: "NEWS",
        titleZh: "Hugging Face 新闻更偏向工具与社区协作",
        titleEn: "Hugging Face news leans toward tooling and collaboration",
        summaryZh: "适合补足社区驱动工具、模型托管和工程实践的公开信息。",
        summaryEn: "Useful for following community tooling, hosting, and engineering practice.",
        sourceName: "Hugging Face",
        sourceUrl: "https://huggingface.co/blog",
        externalUrl: "https://huggingface.co/blog",
        publishedAt: "2026-06-16T00:00:00.000Z",
        heatScore: 82,
        tags: ["Hugging Face", "Tools", "Community"],
      },
      {
        id: "news-08",
        kind: "NEWS",
        titleZh: "Perplexity 的产品节奏更强调搜索入口体验",
        titleEn: "Perplexity keeps pushing search-first product iterations",
        summaryZh: "如果关注 AI 搜索和问答产品形态，这类动态值得长期盯着。",
        summaryEn: "Worth tracking if you care about AI-native search and answer products.",
        sourceName: "Perplexity",
        sourceUrl: "https://www.perplexity.ai/hub/blog",
        externalUrl: "https://www.perplexity.ai/hub/blog",
        publishedAt: "2026-06-15T00:00:00.000Z",
        heatScore: 79,
        tags: ["Perplexity", "Search", "Product"],
      },
    ],
  },
  tech: {
    key: "tech",
    titleZh: "AI 技术",
    titleEn: "AI Technology",
    updatedAt: "2026-06-24T00:00:00.000Z",
    featuredItem: null,
    items: [
      {
        id: "tech-01",
        kind: "TECH",
        titleZh: "Hugging Face 热门论文适合快速看前沿方向",
        titleEn: "Hugging Face papers are a fast signal for frontier direction",
        summaryZh: "适合快速补充近期论文主题，再回头挑值得深入实现的方向。",
        summaryEn: "Useful for scanning papers first and picking what deserves implementation effort.",
        sourceName: "Hugging Face",
        sourceUrl: "https://huggingface.co/papers",
        externalUrl: "https://huggingface.co/papers",
        publishedAt: "2026-06-23T00:00:00.000Z",
        heatScore: 97,
        tags: ["Papers", "LLM", "Engineering"],
      },
      {
        id: "tech-02",
        kind: "TECH",
        titleZh: "Anthropic Engineering 更适合看系统权衡",
        titleEn: "Anthropic Engineering is better for system tradeoffs",
        summaryZh: "如果想看上下文、系统设计和真实工程取舍，这一类内容很有价值。",
        summaryEn: "High-value material for people studying context handling and real system tradeoffs.",
        sourceName: "Anthropic Engineering",
        sourceUrl: "https://www.anthropic.com/engineering",
        externalUrl: "https://www.anthropic.com/engineering",
        publishedAt: "2026-06-22T00:00:00.000Z",
        heatScore: 94,
        tags: ["Systems", "Context", "Infra"],
      },
      {
        id: "tech-03",
        kind: "TECH",
        titleZh: "arXiv AI 近期待补充的是研究覆盖面",
        titleEn: "Recent arXiv AI tracking adds breadth more than implementation detail",
        summaryZh: "更适合补全研究覆盖面，再结合工程文章判断落地价值。",
        summaryEn: "Useful for breadth first, then filtered through engineering value.",
        sourceName: "arXiv",
        sourceUrl: "https://arxiv.org/list/cs.AI/recent",
        externalUrl: "https://arxiv.org/list/cs.AI/recent",
        publishedAt: "2026-06-21T00:00:00.000Z",
        heatScore: 88,
        tags: ["arXiv", "Research", "AI"],
      },
      {
        id: "tech-04",
        kind: "TECH",
        titleZh: "LangChain / LangGraph 更适合看流程编排模式",
        titleEn: "LangChain and LangGraph are best read as orchestration patterns",
        summaryZh: "关注的不是库本身，而是它们如何组织检索、工具调用和状态流转。",
        summaryEn: "The main value is how they model retrieval, tool use, and stateful flows.",
        sourceName: "LangChain",
        sourceUrl: "https://blog.langchain.dev/",
        externalUrl: "https://blog.langchain.dev/",
        publishedAt: "2026-06-20T00:00:00.000Z",
        heatScore: 86,
        tags: ["LangChain", "Agents", "Workflow"],
      },
      {
        id: "tech-05",
        kind: "TECH",
        titleZh: "Ollama 生态更偏本地模型部署体验",
        titleEn: "Ollama coverage is most useful for local model deployment",
        summaryZh: "适合关注本地模型运行、资源约束和开发时调试手感。",
        summaryEn: "Best for tracking local model serving and practical development ergonomics.",
        sourceName: "Ollama",
        sourceUrl: "https://ollama.com/blog",
        externalUrl: "https://ollama.com/blog",
        publishedAt: "2026-06-18T00:00:00.000Z",
        heatScore: 83,
        tags: ["Ollama", "Local LLM", "Serving"],
      },
      {
        id: "tech-06",
        kind: "TECH",
        titleZh: "向量检索实践应重点看召回与排序协同",
        titleEn: "Vector retrieval practice should focus on recall and reranking",
        summaryZh: "真正影响结果的通常不是单个模型，而是召回、过滤、重排这一整段链路。",
        summaryEn: "The important piece is usually the retrieval chain, not one isolated model.",
        sourceName: "Engineering Notes",
        sourceUrl: "https://github.com/openai/openai-cookbook",
        externalUrl: "https://github.com/openai/openai-cookbook",
        publishedAt: "2026-06-17T00:00:00.000Z",
        heatScore: 81,
        tags: ["RAG", "Retrieval", "Ranking"],
      },
      {
        id: "tech-07",
        kind: "TECH",
        titleZh: "多模态工具链的关键在输入预处理与成本控制",
        titleEn: "Multimodal toolchains hinge on preprocessing and cost control",
        summaryZh: "视觉、语音、文本联动看起来华丽，但真正稳定的前提是输入治理。",
        summaryEn: "Cross-modal stacks only stay usable when preprocessing is disciplined.",
        sourceName: "Practical Notes",
        sourceUrl: "https://huggingface.co/blog",
        externalUrl: "https://huggingface.co/blog",
        publishedAt: "2026-06-16T00:00:00.000Z",
        heatScore: 79,
        tags: ["Multimodal", "Preprocess", "Cost"],
      },
      {
        id: "tech-08",
        kind: "TECH",
        titleZh: "Prompt 不该单独讨论，应该放回流程里看",
        titleEn: "Prompt design makes sense only inside a full workflow",
        summaryZh: "单独调 prompt 的收益有限，结合检索、工具和状态管理更符合工程现实。",
        summaryEn: "Prompt tuning alone is limited; workflow context changes the outcome far more.",
        sourceName: "Workflow Notes",
        sourceUrl: "https://www.anthropic.com/engineering",
        externalUrl: "https://www.anthropic.com/engineering",
        publishedAt: "2026-06-15T00:00:00.000Z",
        heatScore: 76,
        tags: ["Prompt", "Workflow", "Agents"],
      },
    ],
  },
  github: {
    key: "github",
    titleZh: "热门仓库",
    titleEn: "Trending Repositories",
    updatedAt: "2026-06-24T00:00:00.000Z",
    featuredItem: null,
    items: [
      {
        id: "github-01",
        kind: "GITHUB",
        titleZh: "microsoft/autogen",
        titleEn: "microsoft/autogen",
        summaryZh: "多智能体与自动编排方向的代表仓库，适合观察 agent 工程实践。",
        summaryEn: "A representative repository for multi-agent orchestration practice.",
        sourceName: "GitHub",
        sourceUrl: "https://github.com",
        externalUrl: "https://github.com/microsoft/autogen",
        publishedAt: "2026-06-23T00:00:00.000Z",
        heatScore: 95,
        tags: ["agent", "automation", "llm"],
        metrics: { githubStars: 54000, githubForks: 8200, githubStarDelta30d: 3000 },
      },
      {
        id: "github-02",
        kind: "GITHUB",
        titleZh: "openai/openai-cookbook",
        titleEn: "openai/openai-cookbook",
        summaryZh: "覆盖 API 用法、工作流模式和参考实现，适合直接上手。",
        summaryEn: "A practical repo for API usage, workflow patterns, and reference implementations.",
        sourceName: "GitHub",
        sourceUrl: "https://github.com",
        externalUrl: "https://github.com/openai/openai-cookbook",
        publishedAt: "2026-06-22T00:00:00.000Z",
        heatScore: 92,
        tags: ["openai", "cookbook", "api"],
        metrics: { githubStars: 69000, githubForks: 11500, githubStarDelta30d: 2000 },
      },
      {
        id: "github-03",
        kind: "GITHUB",
        titleZh: "anthropics/anthropic-cookbook",
        titleEn: "anthropics/anthropic-cookbook",
        summaryZh: "适合对比不同模型接入方式和工程示例结构。",
        summaryEn: "Good for comparing model integration patterns and implementation style.",
        sourceName: "GitHub",
        sourceUrl: "https://github.com",
        externalUrl: "https://github.com/anthropics/anthropic-cookbook",
        publishedAt: "2026-06-21T00:00:00.000Z",
        heatScore: 88,
        tags: ["anthropic", "cookbook", "integration"],
        metrics: { githubStars: 23000, githubForks: 2800, githubStarDelta30d: 1800 },
      },
      {
        id: "github-04",
        kind: "GITHUB",
        titleZh: "langchain-ai/langgraph",
        titleEn: "langchain-ai/langgraph",
        summaryZh: "更适合看有状态流程编排，而不是单步问答。",
        summaryEn: "Best read as a stateful workflow orchestration reference.",
        sourceName: "GitHub",
        sourceUrl: "https://github.com",
        externalUrl: "https://github.com/langchain-ai/langgraph",
        publishedAt: "2026-06-20T00:00:00.000Z",
        heatScore: 86,
        tags: ["workflow", "state", "agent"],
        metrics: { githubStars: 16000, githubForks: 2100, githubStarDelta30d: 2400 },
      },
      {
        id: "github-05",
        kind: "GITHUB",
        titleZh: "huggingface/transformers",
        titleEn: "huggingface/transformers",
        summaryZh: "经典模型工具链，依旧是学习和实验的基础仓库。",
        summaryEn: "Still a baseline repository for learning and experimentation.",
        sourceName: "GitHub",
        sourceUrl: "https://github.com",
        externalUrl: "https://github.com/huggingface/transformers",
        publishedAt: "2026-06-19T00:00:00.000Z",
        heatScore: 84,
        tags: ["models", "nlp", "tooling"],
        metrics: { githubStars: 148000, githubForks: 31000, githubStarDelta30d: 1700 },
      },
      {
        id: "github-06",
        kind: "GITHUB",
        titleZh: "vllm-project/vllm",
        titleEn: "vllm-project/vllm",
        summaryZh: "偏向高性能推理服务与吞吐优化，适合看部署层问题。",
        summaryEn: "High-signal for inference serving and throughput optimization.",
        sourceName: "GitHub",
        sourceUrl: "https://github.com",
        externalUrl: "https://github.com/vllm-project/vllm",
        publishedAt: "2026-06-18T00:00:00.000Z",
        heatScore: 82,
        tags: ["serving", "inference", "performance"],
        metrics: { githubStars: 42000, githubForks: 6700, githubStarDelta30d: 2600 },
      },
      {
        id: "github-07",
        kind: "GITHUB",
        titleZh: "ollama/ollama",
        titleEn: "ollama/ollama",
        summaryZh: "本地模型部署体验很直接，适合本机工作流实验。",
        summaryEn: "A practical repo for local model deployment workflows.",
        sourceName: "GitHub",
        sourceUrl: "https://github.com",
        externalUrl: "https://github.com/ollama/ollama",
        publishedAt: "2026-06-17T00:00:00.000Z",
        heatScore: 79,
        tags: ["local", "llm", "runtime"],
        metrics: { githubStars: 122000, githubForks: 9900, githubStarDelta30d: 4300 },
      },
      {
        id: "github-08",
        kind: "GITHUB",
        titleZh: "crewAIInc/crewAI",
        titleEn: "crewAIInc/crewAI",
        summaryZh: "适合看偏任务分工型的多角色 agent 组织方式。",
        summaryEn: "Useful for studying role-based multi-agent task decomposition.",
        sourceName: "GitHub",
        sourceUrl: "https://github.com",
        externalUrl: "https://github.com/crewAIInc/crewAI",
        publishedAt: "2026-06-16T00:00:00.000Z",
        heatScore: 77,
        tags: ["agents", "roles", "automation"],
        metrics: { githubStars: 39000, githubForks: 5200, githubStarDelta30d: 2100 },
      },
    ],
  },
};

export const DEVELOPER_REPOSITORY_GROUPS = {
  project: [
    { slug: "qiuai", name: "QiuAi", summary: "桌面端 AI 工具主项目。", githubUrl: "https://github.com/QiuShuiqaq/QiuAi" },
    { slug: "camai-sec", name: "CamAI-Sec", summary: "偏视觉与安全场景的项目实验。", githubUrl: "https://github.com/QiuShuiqaq/CamAI-Sec" },
    { slug: "qiuai-design", name: "QiuAi-design", summary: "围绕 QiuAi 的设计稿与视觉资产整理。", githubUrl: "https://github.com/QiuShuiqaq/QiuAi-design" },
    { slug: "qiuai-edpaper", name: "QiuAi-edpaper", summary: "和项目资料、文稿、输出物相关的仓库。", githubUrl: "https://github.com/QiuShuiqaq/QiuAi-edpaper" },
    { slug: "qiuai-editor", name: "QiuAI-editor", summary: "编辑器方向的独立尝试。", githubUrl: "https://github.com/QiuShuiqaq/QiuAI-editor" },
    { slug: "zhigu-app", name: "ZhiGu_app", summary: "应用侧产品化实验。", githubUrl: "https://github.com/QiuShuiqaq/ZhiGu_app" },
    { slug: "qiuai-agent", name: "QiuAi-agent", summary: "面向 agent 能力与执行链路的项目。", githubUrl: "https://github.com/QiuShuiqaq/QiuAi-agent" },
  ],
  skills: [
    { slug: "dev-orchestration-assistant", name: "Dev-Orchestration-Assistant", summary: "开发编排助手相关能力。", githubUrl: "https://github.com/QiuShuiqaq/Dev-Orchestration-Assistant" },
    { slug: "web-design-guidelines", name: "web-design-guidelines", summary: "网页设计与审查准则。", githubUrl: "https://github.com/QiuShuiqaq/web-design-guidelines" },
    { slug: "spec-driven-development", name: "spec-driven-development", summary: "规格驱动开发方法。", githubUrl: "https://github.com/QiuShuiqaq/spec-driven-development" },
    { slug: "shipping-and-launch", name: "shipping-and-launch", summary: "上线发布与交付检查能力。", githubUrl: "https://github.com/QiuShuiqaq/shipping-and-launch" },
    { slug: "security-best-practices", name: "security-best-practices", summary: "安全最佳实践审查能力。", githubUrl: "https://github.com/QiuShuiqaq/security-best-practices" },
    { slug: "react-best-practices", name: "react-best-practices", summary: "React / Next 性能与模式经验。", githubUrl: "https://github.com/QiuShuiqaq/react-best-practices" },
    { slug: "planning-and-task-breakdown", name: "planning-and-task-breakdown", summary: "任务拆解与执行顺序设计。", githubUrl: "https://github.com/QiuShuiqaq/planning-and-task-breakdown" },
    { slug: "performance-optimization", name: "performance-optimization", summary: "性能定位与优化流程。", githubUrl: "https://github.com/QiuShuiqaq/performance-optimization" },
    { slug: "incremental-implementation", name: "incremental-implementation", summary: "增量式实现与分片交付方法。", githubUrl: "https://github.com/QiuShuiqaq/incremental-implementation" },
    { slug: "gh-fix-ci", name: "gh-fix-ci", summary: "GitHub CI 故障排查能力。", githubUrl: "https://github.com/QiuShuiqaq/gh-fix-ci" },
    { slug: "gh-address-comments", name: "gh-address-comments", summary: "处理 GitHub 评审评论的工作流。", githubUrl: "https://github.com/QiuShuiqaq/gh-address-comments" },
    { slug: "documentation-and-adrs", name: "documentation-and-adrs", summary: "文档与架构决策记录整理。", githubUrl: "https://github.com/QiuShuiqaq/documentation-and-adrs" },
    { slug: "development-workflow-router", name: "development-workflow-router", summary: "按开发阶段路由处理能力。", githubUrl: "https://github.com/QiuShuiqaq/development-workflow-router" },
    { slug: "define-goal", name: "define-goal", summary: "目标定义与可衡量结果设计。", githubUrl: "https://github.com/QiuShuiqaq/define-goal" },
    { slug: "debugging-and-error-recovery", name: "debugging-and-error-recovery", summary: "系统化排错与恢复流程。", githubUrl: "https://github.com/QiuShuiqaq/debugging-and-error-recovery" },
    { slug: "code-review-and-quality", name: "code-review-and-quality", summary: "代码审查与质量评估能力。", githubUrl: "https://github.com/QiuShuiqaq/code-review-and-quality" },
    { slug: "cli-creator", name: "cli-creator", summary: "命令行工具设计与封装。", githubUrl: "https://github.com/QiuShuiqaq/cli-creator" },
    { slug: "api-and-interface-design", name: "api-and-interface-design", summary: "接口与模块边界设计。", githubUrl: "https://github.com/QiuShuiqaq/api-and-interface-design" },
    { slug: "clear-development-garbage", name: "clear_development_garbage", summary: "清理开发垃圾与临时产物。", githubUrl: "https://github.com/QiuShuiqaq/clear_development_garbage" },
  ],
};

export const DEVELOPER_MANIFESTO_ZH = [
  "技术的本质是服务于人类，而人类社会长期困于无休止的同质化竞争，大量生命消耗在低效内耗之中。我始终相信，人工智能的终极使命，是成为全人类的共同福祉，将人从无意义的竞争里解放出来，让每个人尽情探寻生命的意义，最终走向“天下为公”的大同社会。",
  "AI 能实现人类思维的自由。它承接绝大多数重复性、机械性的脑力与体力劳动，将人从繁琐事务与生存压力中释放，让个体得以将精力投向创造、审美与自我探索，实现精神与思维的真正舒展。",
  "AI 能实现人类主体的平等。它打破信息与资源的地域、阶层壁垒，让优质教育、医疗、知识服务低成本触达每一个人，不因出身、财富与地域产生悬殊差距，为所有人赋予平等的发展起点与自我实现的可能。",
  "AI 能实现社会视角的公正。它以客观数据与统一规则运行，规避人情偏向、主观偏见与利益裹挟，在公共资源分配、社会机会遴选、公共服务供给中保持中立透明，让公平正义拥有稳定的技术支撑。",
  "AI 能实现社会法治的智慧。智慧法治体系借助 AI 实现精准执法、高效司法与普惠普法，降低个体维权成本，提升社会治理效率，让规则覆盖社会每一处角落，为大同社会筑牢坚实的秩序根基。",
  "当 AI 不再是竞争的工具，而是全人类共享的福祉，人便能真正回归生命本身，在热爱与联结中抵达理想的大同之境。",
];
