ALTER TYPE "PlanCode" ADD VALUE IF NOT EXISTS 'ENTERPRISE_BASIC_MONTHLY';
ALTER TYPE "PlanCode" ADD VALUE IF NOT EXISTS 'ENTERPRISE_BASIC_ANNUAL';
ALTER TYPE "PlanCode" ADD VALUE IF NOT EXISTS 'ENTERPRISE_STANDARD_MONTHLY';
ALTER TYPE "PlanCode" ADD VALUE IF NOT EXISTS 'ENTERPRISE_STANDARD_ANNUAL';
ALTER TYPE "PlanCode" ADD VALUE IF NOT EXISTS 'ENTERPRISE_PRO_MONTHLY';
ALTER TYPE "PlanCode" ADD VALUE IF NOT EXISTS 'ENTERPRISE_PRO_ANNUAL';
