export type PlanCode =
  | 'PERSONAL_FREE'
  | 'PERSONAL_MEMBER_MONTHLY'
  | 'PERSONAL_MEMBER_ANNUAL'
  | 'ENTERPRISE_BASIC_MONTHLY'
  | 'ENTERPRISE_BASIC_ANNUAL'
  | 'ENTERPRISE_STANDARD_MONTHLY'
  | 'ENTERPRISE_STANDARD_ANNUAL'
  | 'ENTERPRISE_PRO_MONTHLY'
  | 'ENTERPRISE_PRO_ANNUAL'
  | 'ENTERPRISE_MONTHLY'
  | 'ENTERPRISE_ANNUAL'
  | 'ENTERPRISE_CUSTOM';
