import type { StudioContent, StudioLocalizedText } from "@/types/studio";

const UPDATED_AT = "2026-07-15T00:00:00.000Z";

function t(zh: string, en: string): StudioLocalizedText {
  return { zh, en };
}

export const defaultStudioContent: StudioContent = {
  version: 1,
  updatedAt: UPDATED_AT,
  home: {
    eyebrow: t("QiuAI WorkOS", "QiuAI WorkOS"),
    title: t("企业 AI 数字员工与数字工厂工作系统", "Enterprise AI work system for digital workers and digital factories"),
    subtitle: t(
      "把数字员工、数字工厂、企业知识库、模型配置和 Windows 桌面端工具收束到一套可安装、可管理、可交付产物的工作系统里。",
      "Unifies digital workers, digital factories, enterprise knowledge bases, model configuration, and Windows desktop tooling into one installable work system.",
    ),
    primaryCta: t("下载客户端", "Download client"),
    secondaryCta: t("进入企业控制台", "Open console"),
    tertiaryCta: t("联系合作", "Contact"),
  },
  metrics: [
    {
      id: "metric-ai-projects",
      label: t("AI 项目", "AI Projects"),
      value: "12+",
      note: t("覆盖内容生产、设计、知识库、自动化与平台运营", "Content, design, knowledge, automation, and platform operations"),
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "metric-open-source",
      label: t("开源项目", "Open Source"),
      value: "20+",
      note: t("沉淀可复用工程能力与公开作品集", "Reusable engineering assets and public repositories"),
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "metric-scenarios",
      label: t("覆盖场景", "Scenarios"),
      value: "5",
      note: t("企业、教育、科研、电商、设计", "Business, education, research, commerce, and design"),
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "metric-directions",
      label: t("技术方向", "Technical Tracks"),
      value: "6",
      note: t("LLM、Agent、RAG、MCP、Vision AI、SaaS", "LLM, Agent, RAG, MCP, Vision AI, and SaaS"),
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  trustedLogos: [
    {
      id: "logo-commerce",
      name: t("跨境电商团队", "Cross-border Commerce Team"),
      category: t("商品内容与运营", "Product content and operations"),
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "logo-education",
      name: t("教育机构", "Education Organization"),
      category: t("课件与知识库", "Courseware and knowledge base"),
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "logo-research",
      name: t("科研团队", "Research Team"),
      category: t("资料整理与 PPT", "Research materials and slides"),
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "logo-design",
      name: t("设计团队", "Design Team"),
      category: t("AI 可编辑设计", "Editable AI design"),
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "logo-operations",
      name: t("企业运营团队", "Operations Team"),
      category: t("流程自动化", "Workflow automation"),
      sortOrder: 50,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  solutions: [
    {
      id: "solution-knowledge-base",
      iconKey: "knowledge",
      title: t("企业 AI 知识库", "Enterprise AI Knowledge Base"),
      summary: t("把散落的文档、制度、产品资料和历史经验整理成可检索、可追溯的知识系统。", "Turn scattered documents and internal knowledge into searchable, traceable AI answers."),
      problems: [t("资料分散，员工反复问同样问题。", "Knowledge is scattered and repetitive questions waste time.")],
      capabilities: [t("文档清洗、向量检索、权限边界、引用溯源。", "Document cleaning, vector retrieval, permission boundaries, and citations.")],
      tags: ["RAG", "Knowledge Base", "LLM"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-agent",
      iconKey: "agent",
      title: t("AI Agent 与数字员工", "AI Agents and Digital Workers"),
      summary: t("围绕具体业务目标构建能调用工具、推进流程、交付结果的智能体。", "Build executable agents that can use tools and move real workflows forward."),
      problems: [t("人工操作链路长，重复流程占用研发和运营时间。", "Long manual workflows consume engineering and operations time.")],
      capabilities: [t("任务拆解、工具调用、日志追踪、人工接管。", "Task planning, tool calling, logs, and human handoff.")],
      tags: ["Agent", "Automation", "Workflow"],
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-workflow",
      iconKey: "workflow",
      title: t("AI 工作流与办公自动化", "AI Workflow and Office Automation"),
      summary: t("连接资料整理、内容生成、表格处理、网页操作和审批流程，形成稳定的自动化链路。", "Connect content, spreadsheets, browser tasks, and approvals into stable automation flows."),
      problems: [t("大量办公流程依赖复制粘贴和人工检查。", "Office work relies on copy-paste and manual checking.")],
      capabilities: [t("浏览器自动化、批量处理、异常重试、结果导出。", "Browser automation, batch processing, retries, and exports.")],
      tags: ["Automation", "Playwright", "Operations"],
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-saas",
      iconKey: "saas",
      title: t("AI SaaS 与运营平台", "AI SaaS and Operations Platforms"),
      summary: t("从用户、授权、订单、钱包、算力、任务队列到后台运营，构建可商业化的 AI 产品基础设施。", "Build commercial AI product infrastructure across users, licenses, orders, wallets, compute, and admin operations."),
      problems: [t("AI 原型能跑，但缺少可收费、可运营、可维护的平台能力。", "AI prototypes work, but lack monetization and operations infrastructure.")],
      capabilities: [t("授权、计费、资源池、后台管理、产品隔离。", "Licensing, billing, resource pools, admin console, and product isolation.")],
      tags: ["SaaS", "Billing", "Platform"],
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-vision",
      iconKey: "vision",
      title: t("智能视觉与图像处理", "Vision AI and Image Workflows"),
      summary: t("结合图像生成、图像编辑、OCR、视觉检测与传统图像处理，落地可控的视觉生产链路。", "Combine image generation, editing, OCR, detection, and classic image processing into controllable production flows."),
      problems: [t("视觉任务结果不可控，人工返工成本高。", "Vision outputs are hard to control and expensive to rework.")],
      capabilities: [t("图像生成、局部编辑、抠图、OCR、视觉校验。", "Image generation, local editing, matting, OCR, and visual checks.")],
      tags: ["Vision AI", "OCR", "Image"],
      sortOrder: 50,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-design",
      iconKey: "design",
      title: t("AI 设计生产力", "AI Design Productivity"),
      summary: t("面向设计师的 AI 辅助设计流程，让图片、文字和布局保持图层可编辑。", "AI-assisted design workflows with editable layers instead of one-shot flattened bitmaps."),
      problems: [t("AI 生图不可编辑，设计师二次修改成本高。", "Generated images are not editable and create rework for designers.")],
      capabilities: [t("图层识别、素材生成、局部修改、可编辑导出。", "Layer recognition, asset generation, local edits, and editable export.")],
      tags: ["Design", "Layer", "AI Image"],
      sortOrder: 60,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  projects: [
    {
      id: "project-qiuai",
      slug: "qiuai",
      title: t("QiuAi", "QiuAi"),
      subtitle: t("AI 内容生产与电商素材工具", "AI content and commerce asset production tool"),
      summary: t("面向电商与内容运营的桌面 AI 工具，支持标题、描述、图片、视频等多环节生产。", "A desktop AI tool for commerce and content teams across titles, descriptions, images, and video."),
      problem: t("内容生产链路长，上游模型不稳定时容易阻塞整组任务。", "Content workflows are long and upstream model instability can block whole jobs."),
      value: t("将 AI 生产流程产品化，提升批量内容生成和结果管理效率。", "Productizes AI production workflows for batch generation and result management."),
      architecture: t("桌面端、授权平台、算力钱包、任务队列与模型供应商适配。", "Desktop client, license platform, wallet, task queue, and model provider adapters."),
      techStack: ["Vue", "Electron", "Node.js", "AI API", "License Platform"],
      coverImage: null,
      screenshots: [],
      demoUrl: null,
      githubUrl: "https://github.com/QiuShuiqaq",
      status: t("持续开发", "Active"),
      tags: ["Desktop", "AI Content", "Commerce"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "project-qiuai-designer",
      slug: "qiuai-designer",
      title: t("QiuAi Designer", "QiuAi Designer"),
      subtitle: t("面向设计师的可编辑 AI 设计工具", "Editable AI design tool for designers"),
      summary: t("通过图层方式承接 AI 生成和局部编辑，让设计师可以继续微调文字、图片和布局。", "Uses layers to keep AI-generated assets editable for text, images, and layouts."),
      problem: t("传统 AI 生图缺少图层概念，修改文案或元素时常常需要整张重做。", "Most AI image tools lack layers, forcing full regeneration for small changes."),
      value: t("降低设计返工成本，让 AI 从灵感工具变成可控生产工具。", "Reduces rework and turns AI into a controllable production tool."),
      architecture: t("画布编辑器、AI 图层上下文、服务端任务与图像编辑模型。", "Canvas editor, AI layer context, server jobs, and image-edit models."),
      techStack: ["Vue", "Canvas", "Fabric.js", "Next.js API", "Vision AI"],
      coverImage: null,
      screenshots: [],
      demoUrl: null,
      githubUrl: "https://github.com/QiuShuiqaq/QiuAi-designer",
      status: t("原型验证", "Prototype"),
      tags: ["Design", "Layer", "Image Edit"],
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "project-qiuai-platform",
      slug: "qiuai-platform",
      title: t("qiuai-platform", "qiuai-platform"),
      subtitle: t("授权、算力、订单与运营平台", "Licensing, compute, order, and operations platform"),
      summary: t("支撑多产品的用户、授权、订单、算力钱包、资源池和后台运营。", "Supports users, licenses, orders, compute wallets, resource pools, and operations across products."),
      problem: t("AI 产品商业化需要稳定的授权、扣费、资源调度和产品隔离。", "Commercial AI products need stable licensing, billing, scheduling, and product isolation."),
      value: t("为多个 AI 产品提供统一但可隔离的商业化基础设施。", "Provides shared but isolated commercial infrastructure for multiple AI products."),
      architecture: t("Next.js、PostgreSQL、Prisma、PM2、Nginx 与产品化 API。", "Next.js, PostgreSQL, Prisma, PM2, Nginx, and productized APIs."),
      techStack: ["Next.js", "PostgreSQL", "Prisma", "PM2", "Nginx"],
      coverImage: null,
      screenshots: [],
      demoUrl: "https://admin-workos.qiuaihub.com",
      githubUrl: "https://github.com/QiuShuiqaq/qiuai-platform",
      status: t("生产运行", "Production"),
      tags: ["SaaS", "Billing", "Admin"],
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "project-enterprise-rag",
      slug: "enterprise-rag",
      title: t("Enterprise RAG Kit", "Enterprise RAG Kit"),
      subtitle: t("企业知识库与问答系统模板", "Enterprise knowledge base and Q&A system template"),
      summary: t("用于快速验证企业文档问答、制度查询、产品资料检索和知识沉淀。", "A template for enterprise document Q&A, policy lookup, product retrieval, and knowledge reuse."),
      problem: t("企业知识分散在文档、聊天记录和人工经验里，难以复用。", "Enterprise knowledge is scattered across files, chat, and human experience."),
      value: t("通过 RAG 让知识可检索、可追溯、可更新。", "Makes knowledge searchable, traceable, and maintainable through RAG."),
      architecture: t("文档解析、向量索引、检索重排、引用溯源与管理后台。", "Document parsing, vector index, reranking, citations, and admin console."),
      techStack: ["RAG", "Vector DB", "LLM", "Next.js", "PostgreSQL"],
      coverImage: null,
      screenshots: [],
      demoUrl: null,
      githubUrl: "https://github.com/QiuShuiqaq",
      status: t("方案模板", "Solution Template"),
      tags: ["RAG", "Knowledge", "Enterprise"],
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  caseStudies: [
    {
      id: "case-commerce-content",
      slug: "commerce-ai-content-system",
      title: t("跨境电商团队 AI 商品内容生产系统", "AI Product Content System for a Commerce Team"),
      industry: t("电商 / 内容运营", "Commerce / Content Operations"),
      background: t("团队需要为多平台商品持续生成标题、卖点、详情页素材和营销图片。", "The team needed continuous titles, selling points, detail-page assets, and marketing images for multiple platforms."),
      painPoints: [
        t("人工生产慢，风格不稳定。", "Manual production was slow and inconsistent."),
        t("图片、标题、描述链路互相阻塞。", "Images, titles, and descriptions blocked each other."),
      ],
      solution: t("搭建 AI 内容生产工作流，将文本、图片和视频结果拆分管理，允许部分结果先返回、后续补齐。", "Built an AI content workflow where text, image, and video results are managed independently and partial outputs can return first."),
      architecture: t("桌面任务中心、服务端模型调用、钱包计费、结果存储与导出。", "Desktop task center, server model calls, wallet billing, result storage, and export."),
      results: [
        t("批量内容生成效率提升。", "Improved batch content production efficiency."),
        t("减少单个模型卡住导致整组任务失败的情况。", "Reduced full-job failures caused by one blocked model."),
      ],
      businessValue: t("让运营团队更快测试商品素材，减少重复人工整理。", "Helps operations teams test product assets faster with less repetitive manual work."),
      reusableCapabilities: [
        t("批量任务调度", "Batch task scheduling"),
        t("模型失败隔离", "Model failure isolation"),
        t("结果导出与存储", "Result export and storage"),
      ],
      coverImage: null,
      screenshots: [],
      metrics: [],
      tags: ["Commerce", "AI Content", "Workflow"],
      isAnonymized: true,
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "case-education-knowledge",
      slug: "education-ai-knowledge-base",
      title: t("教育机构 AI 课件与知识库系统", "AI Courseware and Knowledge System for Education"),
      industry: t("教育 / 培训", "Education / Training"),
      background: t("教师需要整理课程资料、生成课件草稿，并快速查询历史教学内容。", "Teachers needed course material organization, slide drafts, and fast lookup of past teaching content."),
      painPoints: [
        t("资料分散，复用成本高。", "Materials were scattered and costly to reuse."),
        t("课件初稿制作耗时。", "Drafting courseware took too much time."),
      ],
      solution: t("使用知识库和 AI 生成工作流，将课程资料整理成可问答、可生成课件提纲的系统。", "Used knowledge base and AI generation workflows to turn course materials into Q&A and slide-outline generation."),
      architecture: t("文档库、RAG 检索、课件生成模板与人工校对流程。", "Document library, RAG retrieval, courseware templates, and human review."),
      results: [
        t("资料查找时间明显降低。", "Reduced material lookup time."),
        t("教师可以从提纲开始修改，而不是从空白开始。", "Teachers could edit from outlines instead of starting blank."),
      ],
      businessValue: t("让教学内容沉淀为长期可复用资产。", "Turns teaching content into reusable long-term assets."),
      reusableCapabilities: [
        t("RAG 文档问答", "RAG document Q&A"),
        t("课件提纲生成", "Courseware outline generation"),
      ],
      coverImage: null,
      screenshots: [],
      metrics: [],
      tags: ["Education", "RAG", "PPT"],
      isAnonymized: true,
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "case-design-layer-ai",
      slug: "design-layer-ai-workflow",
      title: t("设计团队 AI 可编辑海报生产工具", "Editable AI Poster Workflow for a Design Team"),
      industry: t("设计 / 品牌内容", "Design / Brand Content"),
      background: t("设计师希望 AI 能生成素材，但最终仍然可以编辑文字、图片和布局。", "Designers wanted AI-generated assets while keeping text, images, and layout editable."),
      painPoints: [
        t("传统 AI 生图不可编辑。", "Traditional generated images were not editable."),
        t("局部修改常常需要整图重做。", "Small edits often required full regeneration."),
      ],
      solution: t("围绕图层编辑器接入 AI，对选中图片图层进行局部修改，并保留人工微调空间。", "Integrated AI into a layer editor for selected image-layer edits while preserving manual control."),
      architecture: t("Canvas 图层、AI 上下文抽取、服务端 image-edit 任务与结果回写。", "Canvas layers, AI context extraction, server image-edit jobs, and result patching."),
      results: [
        t("设计师可以对单个素材进行二次生成。", "Designers can regenerate individual assets."),
        t("文字和布局不再被模型锁死。", "Text and layout remain editable."),
      ],
      businessValue: t("让 AI 从一次性灵感工具变成可控的设计生产力工具。", "Turns AI from a one-shot inspiration tool into controlled design productivity."),
      reusableCapabilities: [
        t("图层级 AI 编辑", "Layer-level AI editing"),
        t("可编辑设计输出", "Editable design output"),
      ],
      coverImage: null,
      screenshots: [],
      metrics: [],
      tags: ["Design", "Layer", "Vision AI"],
      isAnonymized: true,
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  openSource: [
    {
      id: "oss-qiuai-platform",
      slug: "qiuai-platform",
      name: "qiuai-platform",
      summary: t("多产品授权、订单、算力、后台运营平台。", "Multi-product licensing, order, compute, and operations platform."),
      techStack: ["Next.js", "Prisma", "PostgreSQL"],
      githubUrl: "https://github.com/QiuShuiqaq/qiuai-platform",
      demoUrl: "https://admin-workos.qiuaihub.com",
      starsLabel: "Internal",
      latestUpdate: "2026-07",
      status: t("生产运行", "Production"),
      tags: ["Platform", "SaaS"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "oss-qiuai-designer",
      slug: "qiuai-designer",
      name: "QiuAi Designer",
      summary: t("面向设计师的 AI 图层编辑工具。", "AI layer editing tool for designers."),
      techStack: ["Vue", "Canvas", "AI"],
      githubUrl: "https://github.com/QiuShuiqaq/QiuAi-designer",
      demoUrl: null,
      starsLabel: "New",
      latestUpdate: "2026-07",
      status: t("开发中", "In Development"),
      tags: ["Design", "AI"],
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  services: [
    {
      id: "service-knowledge-base",
      slug: "enterprise-ai-knowledge-base",
      title: t("企业 AI 知识库", "Enterprise AI Knowledge Base"),
      summary: t("从资料整理、RAG 检索、权限边界到问答体验，构建企业内部知识入口。", "Build internal knowledge access from content cleanup and RAG to permissions and Q&A UX."),
      deliverables: [t("知识库系统", "Knowledge base system"), t("管理后台", "Admin console"), t("部署文档", "Deployment notes")],
      fitFor: [t("制度、产品资料、培训资料分散的团队", "Teams with scattered policies, product docs, and training materials")],
      tags: ["RAG", "Knowledge"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "service-agent-workflow",
      slug: "ai-agent-workflow",
      title: t("AI Agent 与工作流", "AI Agent and Workflow"),
      summary: t("为具体业务流程设计可执行智能体和自动化链路。", "Design executable agents and automation chains for concrete business workflows."),
      deliverables: [t("Agent 原型", "Agent prototype"), t("工具调用接口", "Tool APIs"), t("日志与异常处理", "Logs and recovery")],
      fitFor: [t("有重复流程、跨系统操作和批量处理需求的团队", "Teams with repeated flows, cross-system tasks, and batch work")],
      tags: ["Agent", "Automation"],
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "service-ai-saas",
      slug: "ai-saas-development",
      title: t("AI SaaS 系统开发", "AI SaaS Development"),
      summary: t("从 AI 功能、用户体系、授权计费、钱包扣费到后台运营，搭建可商业化系统。", "Build commercial AI systems across AI features, users, licensing, billing, wallets, and admin operations."),
      deliverables: [t("产品 API", "Product APIs"), t("运营后台", "Operations console"), t("计费与授权", "Billing and licensing")],
      fitFor: [t("准备把 AI 原型做成可收费产品的团队", "Teams turning AI prototypes into paid products")],
      tags: ["SaaS", "Billing"],
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  team: [
    {
      id: "team-ai-product-engineer",
      slug: "ai-product-engineer",
      name: t("QiuShui", "QiuShui"),
      role: t("AI 应用与产品工程", "AI Application and Product Engineering"),
      summary: t("负责 AI 产品设计、全栈开发、桌面端工具、授权平台与企业落地链路。", "Builds AI products, full-stack systems, desktop tools, licensing platforms, and delivery workflows."),
      avatarUrl: null,
      links: [
        { label: "GitHub", href: "https://github.com/QiuShuiqaq" },
        { label: "Website", href: "https://qiuaihub.com" },
      ],
      tags: ["AI Product", "Full Stack", "SaaS"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "team-delivery-network",
      slug: "delivery-network",
      name: t("协作网络", "Delivery Network"),
      role: t("按项目组织的交付伙伴", "Project-based Delivery Partners"),
      summary: t("根据项目需要组合设计、前端、后端、自动化与模型接入协作能力。", "Combines design, frontend, backend, automation, and model integration capabilities as needed."),
      avatarUrl: null,
      links: [],
      tags: ["Delivery", "Design", "Automation"],
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  workSteps: [
    {
      id: "step-discovery",
      title: t("需求诊断", "Discovery"),
      summary: t("明确业务目标、用户角色、数据来源、成本边界和上线约束。", "Define goals, users, data, cost boundaries, and launch constraints."),
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "step-prototype",
      title: t("原型验证", "Prototype"),
      summary: t("先验证最关键链路，避免一开始就做大而全系统。", "Validate the critical path before building a large system."),
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "step-delivery",
      title: t("开发上线", "Build and Launch"),
      summary: t("完成 API、前端、后台、部署、日志和基础运维。", "Deliver APIs, frontend, admin, deployment, logs, and operations basics."),
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "step-iterate",
      title: t("持续优化", "Iterate"),
      summary: t("根据真实使用数据优化稳定性、成本、速度和体验。", "Improve stability, cost, speed, and UX based on real usage."),
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  about: {
    title: t("AI 应用开发工程师，专注企业 AI 落地", "AI application engineer focused on production AI systems"),
    summary: t(
      "关注点不是模型演示，而是如何把 AI 变成可部署、可维护、可运营、能产生业务价值的系统。",
      "My focus is not model demos, but deployable, maintainable, operable AI systems that create business value.",
    ),
    focusAreas: [
      t("AI Agent 与企业工作流", "AI agents and business workflows"),
      t("RAG 与企业知识库", "RAG and enterprise knowledge bases"),
      t("AI SaaS 与授权计费平台", "AI SaaS, licensing, and billing platforms"),
      t("智能视觉与 AI 设计工具", "Vision AI and AI design tools"),
    ],
    capabilities: [
      t("产品设计到工程实现", "Product design to engineering implementation"),
      t("前端、后端、桌面端和部署运维", "Frontend, backend, desktop, and deployment operations"),
      t("模型接入、任务队列、计费与资源管理", "Model integration, queues, billing, and resource management"),
    ],
    stack: ["Next.js", "React", "Vue", "Node.js", "Python", "PostgreSQL", "Prisma", "Electron", "AI APIs"],
    experience: [
      t("长期开发 AI 桌面工具、授权平台和企业工作流系统。", "Long-term work on AI desktop tools, licensing platforms, and business workflow systems."),
      t("关注稳定性、成本控制、可维护性和真实业务交付。", "Focused on stability, cost control, maintainability, and real delivery."),
    ],
  },
  contact: {
    title: t("让 AI 项目进入真实业务流程", "Bring AI projects into real business workflows"),
    summary: t(
      "如果你有企业知识库、AI Agent、工作流自动化、AI SaaS 或智能视觉方向的合作需求，可以通过邮箱或 GitHub 联系。",
      "For enterprise knowledge bases, AI agents, workflow automation, AI SaaS, or vision AI work, contact by email or GitHub.",
    ),
    emails: [
      { label: "QQ", value: "3431752914@qq.com" },
      { label: "163", value: "15005828899@163.com" },
      { label: "Gmail", value: "qiushui1210@gmail.com" },
    ],
    links: [
      { label: "GitHub", href: "https://github.com/QiuShuiqaq" },
      { label: "Website", href: "https://qiuaihub.com" },
    ],
  },
};
