import type { StudioContent, StudioLocalizedText } from "@/types/studio";

const UPDATED_AT = "2026-08-03T00:00:00.000Z";

function t(zh: string, en: string): StudioLocalizedText {
  return { zh, en };
}

export const defaultStudioContent: StudioContent = {
  version: 2,
  updatedAt: UPDATED_AT,
  home: {
    eyebrow: t("QiuAI WorkOS", "QiuAI WorkOS"),
    title: t("企业 AI 数字员工与数字工厂工作系统", "Enterprise AI work system for digital workers and digital factories"),
    subtitle: t(
      "面向 Windows 电脑、本地文件、Office 文档、企业知识库和主流模型配置，把数字员工、数字工厂、任务日志与稳定产物交付整合到一套企业可管理的工作系统里。",
      "For Windows PCs, local files, Office documents, enterprise knowledge bases, and mainstream model setup, QiuAI WorkOS brings digital workers, digital factories, task logs, and reliable artifact delivery into one manageable enterprise system.",
    ),
    primaryCta: t("下载 Windows 客户端", "Download Windows client"),
    secondaryCta: t("进入企业控制台", "Open enterprise console"),
    tertiaryCta: t("联系部署", "Contact for deployment"),
  },
  metrics: [
    {
      id: "metric-local-execution",
      label: t("本地执行", "Local execution"),
      value: "Windows",
      note: t("文件读取、Office 处理、视频处理和产物落地优先在用户电脑完成", "File reading, Office processing, video work, and artifacts are handled on the user's PC first"),
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "metric-batch-image",
      label: t("批量生图", "Batch image generation"),
      value: "50 张/批",
      note: t("跨境商品图工厂支持按产物包批量生成主图、白底图、尺寸图等素材", "The cross-border product image factory generates main images, white-background images, size charts, and more by package"),
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "metric-concurrency",
      label: t("任务并发", "Task concurrency"),
      value: "8 路",
      note: t("适合图片、视频、表格等批量任务，减少长任务等待", "Designed for image, video, and spreadsheet batches to reduce long waits"),
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "metric-traceable-logs",
      label: t("过程可追踪", "Traceable runs"),
      value: "全链路",
      note: t("每个节点的输入、输出、工具调用和失败原因都沉淀到日志", "Node inputs, outputs, tool calls, and failures are recorded in task logs"),
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  trustedLogos: [
    {
      id: "logo-commerce",
      name: t("跨境电商团队", "Cross-border commerce teams"),
      category: t("商品图、Listing、素材批量化", "Product images, listings, and batch assets"),
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "logo-office",
      name: t("企业办公团队", "Enterprise office teams"),
      category: t("文档、表格、会议纪要和知识整理", "Documents, spreadsheets, meeting notes, and knowledge work"),
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "logo-sales",
      name: t("销售与运营团队", "Sales and operations teams"),
      category: t("客户资料、话术、线索和复盘", "Customer files, scripts, leads, and reviews"),
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "logo-healthcare",
      name: t("医疗健康内容团队", "Healthcare content teams"),
      category: t("案例视频筛选、质检和初剪", "Case video screening, QA, and rough cuts"),
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "logo-education",
      name: t("教育培训机构", "Education and training organizations"),
      category: t("课件、资料、知识库和学员服务", "Courseware, materials, knowledge bases, and learner service"),
      sortOrder: 50,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "logo-local-files",
      name: t("重本地文件处理的企业", "Teams with local-file workflows"),
      category: t("本地资料不乱传，结果直接落地", "Keep local files controlled and deliver outputs directly"),
      sortOrder: 60,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  solutions: [
    {
      id: "solution-digital-workers",
      iconKey: "worker",
      title: t("数字员工", "Digital workers"),
      summary: t("面向文档整理、表格整理、文案生成、会议纪要等常见任务，用对话方式接收任务并交付文件。", "For document cleanup, spreadsheet cleanup, copywriting, meeting notes, and similar tasks, digital workers accept requests conversationally and return files."),
      problems: [t("重复办公任务多，普通员工很难判断该配什么模型和工具。", "Office teams have repeated work and users should not need to decide every model and tool.")],
      capabilities: [t("输入输出合约、模型槽位、工具调用、知识库引用、产物写入。", "Input/output contracts, model slots, tool calls, knowledge references, and artifact writing.")],
      tags: ["Digital Worker", "Office", "Artifact"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-digital-factories",
      iconKey: "factory",
      title: t("数字工厂", "Digital factories"),
      summary: t("面向跨境商品图、视频质检剪辑等批量场景，提供上传、参数、队列、输出、日志一体化操作界面。", "For batch scenarios such as product image generation and video QA/editing, factories provide upload, parameters, queues, outputs, and logs in one interface."),
      problems: [t("批量任务靠聊天很难操作，用户需要看得见队列、进度和每个输出物。", "Batch work is hard to run through chat; users need visible queues, progress, and output items.")],
      capabilities: [t("批量上传、并发执行、可编辑输出队列、打包下载、人工复核。", "Batch upload, concurrent execution, editable output queues, package download, and human review.")],
      tags: ["Digital Factory", "Batch", "Review"],
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-windows-client",
      iconKey: "desktop",
      title: t("Windows 桌面端", "Windows desktop client"),
      summary: t("在用户电脑执行本地文件读取、Office 文档生成、视频路径管理和产物落地，减少文件绕路。", "Runs local file reading, Office document generation, video path management, and artifact delivery on the user's PC."),
      problems: [t("企业文件和大视频不适合全部上传到云端处理。", "Enterprise files and large videos should not all be uploaded to the cloud.")],
      capabilities: [t("本地工具、模型配置、设备绑定、工作日志、输出队列。", "Local tools, model setup, device binding, work logs, and output queues.")],
      tags: ["Windows", "Local Files", "Office"],
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-knowledge-base",
      iconKey: "knowledge",
      title: t("企业知识库", "Enterprise knowledge base"),
      summary: t("支持本地知识库和企业知识库合并使用，让数字员工和数字工厂结合企业资料工作。", "Combines local and enterprise knowledge bases so workers and factories can work with company context."),
      problems: [t("模型不知道企业产品、制度和客户资料，输出容易泛化。", "Models lack product, policy, and customer context, so outputs become generic.")],
      capabilities: [t("PDF 知识资产、版本启用、企业同步、任务内检索引用。", "PDF knowledge assets, active versions, enterprise sync, and task-time retrieval.")],
      tags: ["Knowledge", "PDF", "RAG"],
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-model-center",
      iconKey: "model",
      title: t("模型配置中心", "Model configuration center"),
      summary: t("统一管理文本、图片理解、生图、参考图编辑、语音和视频等模型槽位，支持主流供应商与自定义兼容接口。", "Manages model slots for text, image understanding, generation, image editing, speech, and video across mainstream providers and custom compatible APIs."),
      problems: [t("模板不应该绑定死某个模型，用户应能按能力切换已配置模型。", "Templates should not be locked to one model; users should switch configured models by capability.")],
      capabilities: [t("供应商配置、模型拉取、连接测试、能力筛选、自定义配置。", "Provider setup, model fetching, connection tests, capability filtering, and custom configs.")],
      tags: ["Models", "Provider", "BYOK"],
      sortOrder: 50,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "solution-artifacts-logs",
      iconKey: "logs",
      title: t("产物与日志", "Artifacts and logs"),
      summary: t("把用户真正关心的文件、图片、视频、表格和错误信息分开展示，方便定位、复核和交付。", "Separates files, images, videos, spreadsheets, and errors so users can locate, review, and deliver outputs."),
      problems: [t("只看聊天记录无法判断每一步发生了什么，也不方便下载产物。", "Chat alone does not show what happened at each step or make downloads easy.")],
      capabilities: [t("任务日志、输出队列、缩略图、文件定位、打包下载、问题反馈。", "Task logs, output queues, thumbnails, file location, package download, and feedback.")],
      tags: ["Logs", "Outputs", "Feedback"],
      sortOrder: 60,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  projects: [
    {
      id: "product-workos-platform",
      slug: "qiuai-workos",
      title: t("QiuAI WorkOS", "QiuAI WorkOS"),
      subtitle: t("企业 AI 工作系统主产品", "The core enterprise AI work system"),
      summary: t("由 Windows 桌面端、企业 Web 控制台、管理后台和服务端组成，支撑数字员工、数字工厂、授权套餐、知识库和模型配置。", "A Windows desktop client, enterprise web console, admin console, and server platform for digital workers, digital factories, plans, knowledge bases, and model configuration."),
      problem: t("企业想用 AI 处理真实文件和批量流程，但单纯聊天工具很难管理模型、设备、知识库、日志和产物。", "Enterprises need AI for real files and batch workflows, but chat tools do not manage models, devices, knowledge bases, logs, and artifacts well."),
      value: t("把 AI 从单次对话变成可安装、可配置、可复核、可交付的企业工作系统。", "Turns AI from one-off chats into an installable, configurable, reviewable, and deliverable work system."),
      architecture: t("Electron 桌面端、Next.js Web 控制台、Node.js 服务端、PostgreSQL、Prisma、PM2 与 Nginx 部署。", "Electron desktop, Next.js web console, Node.js server, PostgreSQL, Prisma, PM2, and Nginx deployment."),
      techStack: ["Electron", "Next.js", "Node.js", "PostgreSQL", "Prisma"],
      coverImage: null,
      screenshots: [],
      demoUrl: "https://workos.qiuaihub.com",
      githubUrl: "https://github.com/QiuShuiqaq/QiuAi-workOS",
      status: t("第一版发布准备中", "Preparing first release"),
      tags: ["WorkOS", "Desktop", "Enterprise"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "product-digital-workers",
      slug: "digital-workers",
      title: t("数字员工", "Digital Workers"),
      subtitle: t("适合对话式办公任务的 AI 员工", "AI workers for conversational office tasks"),
      summary: t("基础员工可免费使用，企业员工可按权限安装，并可结合企业知识库处理文档、表格、文案、会议等任务。", "Free basic workers and enterprise workers can be installed by permission and use enterprise knowledge for documents, spreadsheets, copy, and meetings."),
      problem: t("用户不想理解节点、变量和工具细节，只想把任务交给一个明确身份的 AI 员工。", "Users do not want nodes, variables, and tool details; they want to assign work to a clear AI role."),
      value: t("用统一模板和输入输出合约控制产物质量，减少每次从零搭建。", "Uses standardized templates and contracts to control artifact quality and reduce repeated setup."),
      architecture: t("数字市场模板、模型槽位、工具节点、知识库绑定、日志和产物节点组成执行链路。", "Marketplace templates, model slots, tool nodes, knowledge binding, logs, and artifact nodes form the execution chain."),
      techStack: ["Workflow", "LLM", "Office Tools", "Knowledge Base"],
      coverImage: null,
      screenshots: [],
      demoUrl: null,
      githubUrl: null,
      status: t("已支持基础模板", "Basic templates supported"),
      tags: ["Worker", "Office", "Knowledge"],
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "product-digital-factories",
      slug: "digital-factories",
      title: t("数字工厂", "Digital Factories"),
      subtitle: t("适合批量任务和可视化输出的 AI 工厂", "AI factories for batch tasks and visual outputs"),
      summary: t("数字工厂提供上传区、参数设置、任务队列、输出队列、模型状态和工作日志，适合商品图、视频质检等复杂流程。", "Digital factories provide upload, parameters, task queues, output queues, model status, and logs for product images, video QA, and other complex workflows."),
      problem: t("复杂批量任务不能只靠聊天，用户需要可控参数、并发处理、逐条复核和打包交付。", "Complex batch work cannot rely on chat only; users need parameters, concurrency, item-level review, and package delivery."),
      value: t("把 AI 能力做成可操作的生产线，让企业直接看进度、看产物、看问题。", "Turns AI capability into an operable production line where teams can see progress, outputs, and problems."),
      architecture: t("工厂模板定义输入、参数、模型槽位、工具节点、输出物类型、状态修改和下载行为。", "Factory templates define inputs, parameters, model slots, tool nodes, output item types, status edits, and downloads."),
      techStack: ["Factory", "Batch", "Queue", "Image", "Video"],
      coverImage: null,
      screenshots: [],
      demoUrl: null,
      githubUrl: null,
      status: t("已支持两个核心工厂", "Two core factories supported"),
      tags: ["Factory", "Batch", "Outputs"],
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "product-asset-center",
      slug: "asset-center",
      title: t("资产中心", "Asset Center"),
      subtitle: t("变量、模型、知识库和模板资产统一管理", "Unified management for variables, models, knowledge bases, and templates"),
      summary: t("把变量命名、模型配置、知识库 PDF、数字员工模板和数字工厂模板沉淀成系统资产，降低后续搭建成本。", "Turns variables, model configs, knowledge PDFs, worker templates, and factory templates into system assets to reduce future setup cost."),
      problem: t("没有统一资产库时，变量名、模型配置和模板会越搭越乱。", "Without a unified asset library, variable names, model setup, and templates become messy over time."),
      value: t("用标准化资产减少重复配置，让后续新增数字员工和数字工厂更稳定。", "Standardized assets reduce repeated configuration and make new workers and factories more stable."),
      architecture: t("服务端定义资产与模板，PC 端按企业和设备权限同步安装和运行。", "The server defines assets and templates; the PC client syncs, installs, and runs them by enterprise and device permissions."),
      techStack: ["Assets", "Models", "Knowledge", "Templates"],
      coverImage: null,
      screenshots: [],
      demoUrl: "https://admin-workos.qiuaihub.com",
      githubUrl: null,
      status: t("已接入新体系", "Connected to the new system"),
      tags: ["Asset", "Model", "Knowledge"],
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  caseStudies: [
    {
      id: "case-cross-border-image-factory",
      slug: "cross-border-product-image-factory",
      title: t("跨境商品图工厂", "Cross-border product image factory"),
      industry: t("跨境电商 / 商品素材", "Cross-border commerce / Product assets"),
      background: t("运营团队拿到一张商品样图后，需要快速生成主图、白底图、尺寸图、场景图、换背景和换模特等多平台素材。", "After receiving a product sample image, operations teams need main images, white-background images, size charts, lifestyle shots, background changes, and model changes for multiple platforms."),
      painPoints: [
        t("单张图反复找设计师处理，周期长。", "Repeated designer handoff for each image slows the team down."),
        t("不同平台尺寸、风格和语言要求不一致。", "Platform size, style, and language requirements vary."),
      ],
      solution: t("在 PC 端上传样图，勾选需要的产物包，设置风格、排除项和图片文字语言，系统并发生成并按缩略图展示输出。", "Users upload sample images on the PC client, select output packages, set style, exclusions, and image text language, then review generated outputs as thumbnails."),
      architecture: t("多模态模型生成提示词，生图或参考图编辑模型生成图片，服务器只记录任务和上游 URL，大文件产物落在本地。", "A multimodal model writes prompts, image generation or reference editing models create images, the server records tasks and upstream URLs, and large artifacts stay local."),
      results: [
        t("支持 50 张/批、8 路并发，适合批量测款。", "Supports 50 images per batch and 8-way concurrency for product testing."),
        t("输出队列可按产物包查看、预览和定位本地文件。", "The output queue can be reviewed by package, previewed, and located on disk."),
      ],
      businessValue: t("让跨境团队更快复制商品素材，减少重复设计沟通和人工整理。", "Helps commerce teams replicate product assets faster with less repetitive design communication and manual sorting."),
      reusableCapabilities: [
        t("批量上传与产物包", "Batch upload and output packages"),
        t("风格与语言控制", "Style and language control"),
        t("缩略图输出队列", "Thumbnail output queue"),
      ],
      coverImage: null,
      screenshots: [],
      metrics: [],
      tags: ["Commerce", "Image", "Factory"],
      isAnonymized: false,
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "case-video-qa-editing-factory",
      slug: "video-qa-editing-factory",
      title: t("视频质检剪辑工厂", "Video QA and rough-cut factory"),
      industry: t("医疗健康内容 / 视频筛选", "Healthcare content / Video screening"),
      background: t("团队有大量用户案例视频，需要先筛掉比例、时长、语音质量和内容表达不合格的视频，再保留合格视频并可选生成初剪合集。", "The team has many user case videos and needs to filter by aspect ratio, duration, speech quality, and content quality, then keep qualified videos and optionally generate rough-cut collections."),
      painPoints: [
        t("人工逐条看视频耗时，筛选标准难统一。", "Manual video review is slow and criteria are hard to keep consistent."),
        t("合格视频、待复核视频和不合格原因需要清晰交付。", "Qualified videos, review-needed videos, and rejection reasons must be delivered clearly."),
      ],
      solution: t("PC 端上传视频文件夹，按可编辑筛选标准逐步筛选，ASR 转写后基于文本判断表达质量，并在输出队列支持预览、改状态、删除和打包下载。", "Users upload a video folder, apply editable screening criteria step by step, use ASR transcripts for expression quality checks, and review outputs with preview, status edits, deletion, and package download."),
      architecture: t("本地视频元信息检测、音频抽取、ASR、筛选规则、可选初剪工具和 Excel/文件夹产物组成链路。", "The flow combines local video metadata checks, audio extraction, ASR, screening rules, optional rough-cut tooling, and Excel/folder artifacts."),
      results: [
        t("先筛选再打分，未达标视频不进入后续流程。", "Filtering happens before scoring, and failed videos do not enter later steps."),
        t("最终输出合格视频地址、筛选明细表和可选初剪合集文件夹。", "Final outputs include qualified video paths, a screening report, and an optional rough-cut collection folder."),
      ],
      businessValue: t("把大量视频初筛和交付整理自动化，审核员只需要处理真正需要人工判断的部分。", "Automates first-pass video screening and delivery sorting so reviewers focus on cases that need human judgment."),
      reusableCapabilities: [
        t("可编辑筛选标准", "Editable screening criteria"),
        t("ASR 转写与质量判断", "ASR transcript and quality checks"),
        t("视频输出队列复核", "Video output queue review"),
      ],
      coverImage: null,
      screenshots: [],
      metrics: [],
      tags: ["Video", "ASR", "Factory"],
      isAnonymized: true,
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "case-office-worker-pack",
      slug: "office-digital-worker-pack",
      title: t("基础办公数字员工包", "Basic office digital worker pack"),
      industry: t("企业办公 / 本地文件", "Enterprise office / Local files"),
      background: t("企业日常会遇到文档整理、表格清洗、会议纪要和文案生成等高频任务，希望免费用户也能快速体验。", "Teams often need document cleanup, spreadsheet cleaning, meeting notes, and copywriting, and free users should be able to try the basics quickly."),
      painPoints: [
        t("普通员工不会搭建工作流，但需要稳定的 Word、Excel、Markdown 等产物。", "Regular employees do not build workflows but still need reliable Word, Excel, Markdown, and similar outputs."),
        t("节点详情不适合暴露给最终用户。", "Node details should not be exposed to end users."),
      ],
      solution: t("提供免费基础数字员工，并把详细节点日志收束到日志侧边栏，聊天区只保留用户能理解的进展和结果。", "Provides free basic workers and moves detailed node logs into the log sidebar while the chat area keeps user-facing progress and results."),
      architecture: t("对话输入、模型节点、Office 工具、产物写入和输出节点串联，PC 端按已配置模型自动运行。", "Conversation input, model nodes, Office tools, artifact writing, and output nodes run on the PC client with configured models."),
      results: [
        t("文档整理专员可将 TXT/PDF 内容整理为正式 Word 文档。", "The document worker can turn TXT/PDF content into formal Word documents."),
        t("表格整理专员可输出结构化表格和异常提示。", "The spreadsheet worker can output structured tables and anomaly notes."),
      ],
      businessValue: t("让企业先用低门槛办公任务建立信任，再逐步安装企业员工和数字工厂。", "Lets companies build trust with low-friction office tasks before installing enterprise workers and factories."),
      reusableCapabilities: [
        t("Office 产物写入", "Office artifact writing"),
        t("任务日志收束", "Task log separation"),
        t("模型槽位切换", "Model slot switching"),
      ],
      coverImage: null,
      screenshots: [],
      metrics: [],
      tags: ["Office", "Worker", "Free"],
      isAnonymized: false,
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  openSource: [
    {
      id: "engineering-workos",
      slug: "qiuai-workos",
      name: "QiuAi-workOS",
      summary: t("QiuAI WorkOS 的桌面端、服务端、企业控制台、管理后台和官网工程。", "The desktop client, server, enterprise console, admin console, and public site for QiuAI WorkOS."),
      techStack: ["Electron", "Next.js", "Node.js", "PostgreSQL"],
      githubUrl: "https://github.com/QiuShuiqaq/QiuAi-workOS",
      demoUrl: "https://workos.qiuaihub.com",
      starsLabel: "Product",
      latestUpdate: "2026-08",
      status: t("产品化中", "Productizing"),
      tags: ["WorkOS", "Enterprise", "Desktop"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "engineering-qiuai-designer",
      slug: "qiuai-designer",
      name: "QiuAi Designer",
      summary: t("面向设计师的 AI 图层编辑方向，是后续视觉生产能力的工程储备。", "An AI layer-editing direction for designers and a foundation for future visual production features."),
      techStack: ["Vue", "Canvas", "AI Image"],
      githubUrl: "https://github.com/QiuShuiqaq/QiuAi-designer",
      demoUrl: null,
      starsLabel: "Research",
      latestUpdate: "2026-07",
      status: t("技术储备", "Engineering reserve"),
      tags: ["Design", "Image", "Layer"],
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  services: [
    {
      id: "service-workos-deployment",
      slug: "workos-deployment",
      title: t("QiuAI WorkOS 部署与初始化", "QiuAI WorkOS deployment and onboarding"),
      summary: t("协助企业完成服务端部署、域名、Nginx、PM2、数据库、套餐权限、客户端下载和设备绑定。", "Helps enterprises set up the server, domains, Nginx, PM2, database, plans, client downloads, and device binding."),
      deliverables: [t("可访问的企业控制台", "Accessible enterprise console"), t("Windows 客户端下载入口", "Windows client download entry"), t("基础权限与套餐配置", "Basic plan and permission setup")],
      fitFor: [t("准备把 WorkOS 正式用于企业内部团队的客户", "Customers preparing to use WorkOS with internal enterprise teams")],
      tags: ["Deployment", "Console", "Device"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "service-digital-worker-setup",
      slug: "digital-worker-setup",
      title: t("数字员工搭建", "Digital worker setup"),
      summary: t("围绕具体岗位和场景搭建企业数字员工，配置输入输出合约、模型槽位、知识库和产物格式。", "Builds enterprise digital workers around roles and scenarios, including contracts, model slots, knowledge bases, and artifact formats."),
      deliverables: [t("数字员工模板", "Digital worker templates"), t("模型与工具配置建议", "Model and tool setup guidance"), t("测试样例与验收标准", "Test cases and acceptance criteria")],
      fitFor: [t("有文档、表格、销售、运营、客服等重复知识工作流程的企业", "Enterprises with repeated knowledge work in documents, spreadsheets, sales, operations, or support")],
      tags: ["Worker", "Template", "Knowledge"],
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "service-digital-factory-rollout",
      slug: "digital-factory-rollout",
      title: t("数字工厂落地", "Digital factory rollout"),
      summary: t("把跨境商品图、视频质检、资料批处理等复杂流程做成可批量操作、可复核、可交付的数字工厂。", "Turns complex flows such as product images, video QA, and document batches into operable, reviewable, deliverable factories."),
      deliverables: [t("工厂流程模板", "Factory workflow template"), t("参数与输出队列设计", "Parameter and output queue design"), t("人工复核和下载规则", "Review and download rules")],
      fitFor: [t("批量任务多、产物需要逐条检查和打包交付的团队", "Teams with batch work that needs item-level review and package delivery")],
      tags: ["Factory", "Batch", "Outputs"],
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "service-knowledge-base",
      slug: "enterprise-knowledge-base",
      title: t("企业知识库整理", "Enterprise knowledge base setup"),
      summary: t("将企业基础信息、产品资料、制度、销售话术和常见问题整理成可同步到设备的 PDF 知识库资产。", "Organizes company profiles, product docs, policies, sales scripts, and FAQs into PDF knowledge assets that sync to devices."),
      deliverables: [t("企业基础知识库 PDF", "Enterprise knowledge PDF"), t("版本启用规则", "Version activation rules"), t("本地与企业知识合并策略", "Local and enterprise knowledge merge strategy")],
      fitFor: [t("希望数字员工输出更贴合企业真实资料的团队", "Teams that want digital worker outputs to match real company knowledge")],
      tags: ["Knowledge", "PDF", "RAG"],
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  team: [
    {
      id: "team-qiuai-product",
      slug: "qiuai-product",
      name: t("QiuAI WorkOS 产品团队", "QiuAI WorkOS Product Team"),
      role: t("企业 AI 产品与工程交付", "Enterprise AI product and engineering delivery"),
      summary: t("负责 QiuAI WorkOS 的产品设计、桌面端、服务端、管理后台、模型接入和企业落地。", "Builds QiuAI WorkOS across product design, desktop client, server, admin console, model integration, and enterprise rollout."),
      avatarUrl: null,
      links: [
        { label: "GitHub", href: "https://github.com/QiuShuiqaq" },
        { label: "Website", href: "https://qiuaihub.com" },
      ],
      tags: ["WorkOS", "AI Product", "Delivery"],
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  workSteps: [
    {
      id: "step-install",
      title: t("下载安装", "Download and install"),
      summary: t("从官网下载 Windows 客户端，完成企业账号登录和设备绑定。", "Download the Windows client, sign in with the enterprise account, and bind the device."),
      sortOrder: 10,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "step-configure",
      title: t("配置模型与知识库", "Configure models and knowledge"),
      summary: t("在 PC 端配置可用模型，在企业端维护企业知识库和套餐权限。", "Configure available models on the PC client, and maintain enterprise knowledge and plans in the web console."),
      sortOrder: 20,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "step-install-workers",
      title: t("安装数字员工或数字工厂", "Install workers or factories"),
      summary: t("从数字市场安装合适的数字员工或数字工厂，缺配置时按提示补齐。", "Install digital workers or factories from the marketplace and complete any missing setup when prompted."),
      sortOrder: 30,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
    {
      id: "step-run-review",
      title: t("运行、复核、交付", "Run, review, and deliver"),
      summary: t("提交任务后查看队列、日志和输出物，必要时人工复核后打包交付。", "After submitting tasks, review queues, logs, and outputs, then package deliverables after human review when needed."),
      sortOrder: 40,
      isVisible: true,
      updatedAt: UPDATED_AT,
    },
  ],
  about: {
    title: t("QiuAI WorkOS：面向企业真实工作的 AI 操作系统", "QiuAI WorkOS: an AI work system for real enterprise workflows"),
    summary: t(
      "QiuAI WorkOS 的重点不是展示模型有多聪明，而是让企业能把本地文件、知识库、模型、工具、任务日志和产物交付放进同一套可管理流程。",
      "QiuAI WorkOS is not about model demos; it puts local files, knowledge bases, models, tools, logs, and artifact delivery into one manageable enterprise workflow.",
    ),
    focusAreas: [
      t("数字员工与企业岗位任务", "Digital workers and role-based tasks"),
      t("数字工厂与批量生产流程", "Digital factories and batch production flows"),
      t("Windows 本地执行与 Office 产物", "Windows local execution and Office artifacts"),
      t("模型配置、知识库和权限管理", "Model setup, knowledge bases, and permissions"),
    ],
    capabilities: [
      t("桌面端、服务端、Web 控制台和管理后台一体化", "Integrated desktop, server, web console, and admin console"),
      t("主流模型供应商与自定义兼容接口接入", "Mainstream providers and custom compatible model APIs"),
      t("任务队列、工作日志、输出队列和问题反馈闭环", "Task queues, work logs, output queues, and feedback loop"),
    ],
    stack: ["Electron", "Next.js", "React", "Node.js", "PostgreSQL", "Prisma", "PM2", "Nginx", "AI APIs"],
    experience: [
      t("已经围绕文档整理、表格整理、跨境商品图和视频质检剪辑沉淀基础模板。", "Includes base templates for document cleanup, spreadsheet cleanup, cross-border product images, and video QA/editing."),
      t("后续可继续扩展行业数字员工和企业数字工厂，但保持统一模型槽位、资产中心和输出规范。", "Future industry workers and factories can expand while keeping unified model slots, asset center, and output conventions."),
    ],
  },
  contact: {
    title: t("把 QiuAI WorkOS 部署到你的企业流程里", "Bring QiuAI WorkOS into your enterprise workflow"),
    summary: t(
      "如果你希望试用 Windows 桌面端、搭建企业数字员工、落地数字工厂或整理企业知识库，可以通过邮箱联系。",
      "Contact us if you want to try the Windows client, build enterprise digital workers, roll out digital factories, or organize an enterprise knowledge base.",
    ),
    emails: [
      { label: "QQ", value: "3431752914@qq.com" },
      { label: "163", value: "15005828899@163.com" },
      { label: "Gmail", value: "qiushui1210@gmail.com" },
    ],
    links: [
      { label: "企业控制台", href: "https://workos.qiuaihub.com" },
      { label: "下载客户端", href: "https://qiuaihub.com/downloads" },
      { label: "GitHub", href: "https://github.com/QiuShuiqaq/QiuAi-workOS" },
    ],
  },
};
