import assert from 'node:assert/strict';

import type { ModelProfile, ToolManifest } from './desktop-contract.js';
import { runDesktopTask } from './desktop-task-runner.js';
import { createMockTaskDetail } from './workbench-data.js';

const modelProfiles: ModelProfile[] = [
  {
    id: 'qiu-general-default',
    providerId: 'provider-local',
    providerName: 'Local Provider',
    modelName: 'general-chat',
    purpose: 'general',
    apiBaseUrl: 'https://model.example/v1',
    apiKey: 'test-api-key'
  }
];

const tools: ToolManifest[] = [
  {
    id: 'web-search',
    name: 'Web Search',
    version: '1.0.0',
    scope: 'hybrid',
    entryPoint: 'api',
    capabilities: ['web_search'],
    requiresApproval: false
  },
  {
    id: 'office-document',
    name: 'Office Document',
    version: '1.0.0',
    scope: 'desktop',
    entryPoint: 'bridge',
    capabilities: ['document_edit'],
    requiresApproval: true
  },
  {
    id: 'local-filesystem',
    name: 'Local Filesystem',
    version: '1.0.0',
    scope: 'desktop',
    entryPoint: 'native',
    capabilities: ['filesystem'],
    requiresApproval: true
  }
];

const task = createMockTaskDetail({
  taskId: 'task-runner-001',
  roleCode: 'ai-ops',
  roleName: 'AI Ops',
  title: 'Prepare weekly customer follow-up summary',
  input: 'Summarize the customer notes and create next actions.',
  state: 'queued',
  artifactCount: 0,
  costCents: 0,
  executionContext: {
    modelProfileIds: ['qiu-general-default'],
    toolIds: ['web-search', 'office-document'],
    knowledgeBindingIds: ['kb-local-folder']
  }
});

const completed = await runDesktopTask({
  task,
  modelProfiles,
  tools,
  knowledgeSources: [
    {
      id: 'kb-local-folder',
      source: 'local_folder',
      label: 'Customer Docs',
      enabled: true,
      createdAt: '2026-07-20T09:55:00.000Z',
      localPath: 'C:\\QiuAI\\CustomerDocs',
      lastIndexedAt: '2026-07-20T09:56:00.000Z',
      summary: 'Customer renewal notes and follow-up SOP.'
    }
  ],
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['web-search'],
  enabledKnowledgeBindingIds: ['kb-local-folder'],
  modelInvoker: async (request) => {
    assert.equal(request.profile.id, 'qiu-general-default');
    assert.equal(request.messages.length, 2);
    assert.match(request.messages[1]?.content ?? '', /Customer Docs/);
    return {
      provider: request.profile.providerName,
      modelName: request.profile.modelName,
      content: 'Customer follow-up summary generated by model.',
      inputTokens: 300,
      outputTokens: 180
    };
  },
  completedAt: '2026-07-20T10:00:00.000Z'
});

assert.equal(completed.task.state, 'completed');
assert.equal(completed.task.artifacts.filter((artifact) => artifact.type !== 'report').length, 1);
assert.equal(completed.task.artifacts.filter((artifact) => artifact.type === 'report').length, 1);
assert.equal(completed.task.artifactCount, 1);
assert.match(
  completed.task.artifacts.find((artifact) => artifact.type !== 'report')?.content ?? '',
  /Customer follow-up summary/
);
assert.equal(completed.task.costRecords.length, 1);
assert.equal(completed.task.costRecords[0]?.inputTokens, 300);
assert.deepEqual(completed.usedToolIds, []);
assert.ok(
  completed.task.executionLogs.some((log) => log.eventType === 'TOOL_BINDING_SKIPPED')
);
assert.ok(
  completed.task.executionLogs.some((log) => log.eventType === 'MODEL_RESPONSE_RECEIVED')
);

let toolCallingModelInvocationCount = 0;
const toolCallingProgressSnapshots: string[][] = [];
const toolCallingProgressArtifactPaths: string[][] = [];
const toolCallingTask = await runDesktopTask({
  task: {
    ...task,
    taskId: 'task-runner-tool-call-001',
    executionContext: {
      modelProfileIds: ['qiu-general-default'],
      toolIds: ['local-filesystem'],
      knowledgeBindingIds: []
    }
  },
  workspaceId: 'workspace-tool-call',
  modelProfiles,
  tools,
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['local-filesystem'],
  enabledKnowledgeBindingIds: [],
  modelInvoker: async (request) => {
    toolCallingModelInvocationCount += 1;
    if (toolCallingModelInvocationCount === 1) {
      return {
        provider: request.profile.providerName,
        modelName: request.profile.modelName,
        content:
          'QIUAI_DESKTOP_TOOL_CALL: {"toolId":"local-filesystem","action":"filesystem.write_text_file","input":{"folder":"reports","fileName":"weekly-summary","content":"Generated weekly summary"}}',
        inputTokens: 120,
        outputTokens: 60
      };
    }

    assert.match(request.messages.at(-1)?.content ?? '', /Desktop tool result/);
    return {
      provider: request.profile.providerName,
      modelName: request.profile.modelName,
      content: 'Final result generated after local filesystem tool execution.',
      inputTokens: 160,
      outputTokens: 90
    };
  },
  desktopToolInvoker: async (request) => {
    assert.equal(request.workspaceId, 'workspace-tool-call');
    assert.equal(request.toolId, 'local-filesystem');
    assert.equal(request.action, 'filesystem.write_text_file');
    assert.equal(request.input.fileName, 'weekly-summary');

    return {
      toolId: request.toolId,
      action: request.action,
      ok: true,
      output: {
        localPath: 'C:\\QiuAI\\workspace\\reports\\weekly-summary.md'
      }
    };
  },
  onProgress: (progressTask) => {
    toolCallingProgressSnapshots.push(progressTask.executionLogs.map((log) => log.eventType));
    toolCallingProgressArtifactPaths.push(
      progressTask.artifacts.flatMap((artifact) => (artifact.localPath ? [artifact.localPath] : []))
    );
  },
  completedAt: '2026-07-20T10:00:10.000Z'
});

assert.equal(toolCallingModelInvocationCount, 2);
assert.equal(toolCallingTask.task.state, 'completed');
assert.deepEqual(toolCallingTask.usedToolIds, ['local-filesystem']);
assert.equal(toolCallingTask.task.artifacts.length, 2);
assert.equal(toolCallingTask.task.artifacts[0]?.localPath, 'C:\\QiuAI\\workspace\\reports\\weekly-summary.md');
assert.match(toolCallingTask.task.artifacts[1]?.content ?? '', /after local filesystem tool execution/);
assert.ok(toolCallingTask.task.executionLogs.some((log) => log.eventType === 'TOOL_CALL_DETECTED'));
assert.ok(toolCallingTask.task.executionLogs.some((log) => log.eventType === 'TOOL_INVOKED'));
assert.ok(toolCallingTask.task.executionLogs.some((log) => log.eventType === 'TOOL_RESULT_RETURNED_TO_MODEL'));
assert.ok(toolCallingProgressSnapshots.some((events) => events.includes('MODEL_REQUEST_STARTED')));
assert.ok(toolCallingProgressSnapshots.some((events) => events.includes('TOOL_CALL_DETECTED')));
assert.ok(toolCallingProgressSnapshots.some((events) => events.includes('TOOL_INVOKED')));
assert.ok(toolCallingProgressSnapshots.some((events) => events.includes('TOOL_RESULT_RETURNED_TO_MODEL')));
assert.ok(
  toolCallingProgressSnapshots.at(-1)?.filter((eventType) => eventType === 'MODEL_REQUEST_STARTED').length === 1
);
assert.ok(
  toolCallingProgressArtifactPaths.some((paths) =>
    paths.includes('C:\\QiuAI\\workspace\\reports\\weekly-summary.md')
  )
);

let officeToolModelInvocationCount = 0;
const officeToolCallingTask = await runDesktopTask({
  task: {
    ...task,
    taskId: 'task-runner-office-tool-call-001',
    executionContext: {
      modelProfileIds: ['qiu-general-default'],
      toolIds: ['office-document'],
      knowledgeBindingIds: []
    }
  },
  workspaceId: 'workspace-office-tool-call',
  modelProfiles,
  tools,
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['office-document'],
  enabledKnowledgeBindingIds: [],
  modelInvoker: async (request) => {
    officeToolModelInvocationCount += 1;
    if (officeToolModelInvocationCount === 1) {
      return {
        provider: request.profile.providerName,
        modelName: request.profile.modelName,
        content:
          'QIUAI_DESKTOP_TOOL_CALL: {"toolId":"office-document","action":"office.write_markdown_document","input":{"title":"Follow-up Plan","folder":"documents","fileName":"follow-up-plan","content":"## Next actions\\n\\n- Call customer owner"}}'
      };
    }

    assert.match(request.messages.at(-1)?.content ?? '', /Desktop tool result/);
    return {
      provider: request.profile.providerName,
      modelName: request.profile.modelName,
      content: 'Final result generated after office document tool execution.'
    };
  },
  desktopToolInvoker: async (request) => {
    assert.equal(request.workspaceId, 'workspace-office-tool-call');
    assert.equal(request.toolId, 'office-document');
    assert.equal(request.action, 'office.write_markdown_document');
    assert.equal(request.input.fileName, 'follow-up-plan');

    return {
      toolId: request.toolId,
      action: request.action,
      ok: true,
      output: {
        localPath: 'C:\\QiuAI\\workspace\\documents\\follow-up-plan.md'
      }
    };
  },
  completedAt: '2026-07-20T10:00:12.000Z'
});

assert.equal(officeToolModelInvocationCount, 2);
assert.equal(officeToolCallingTask.task.state, 'completed');
assert.deepEqual(officeToolCallingTask.usedToolIds, ['office-document']);
assert.equal(officeToolCallingTask.task.artifacts.length, 2);
assert.equal(officeToolCallingTask.task.artifacts[0]?.localPath, 'C:\\QiuAI\\workspace\\documents\\follow-up-plan.md');
assert.match(officeToolCallingTask.task.artifacts[1]?.content ?? '', /office document tool execution/);

let multiToolModelInvocationCount = 0;
const multiToolRequests: Array<{ toolId: string; action: string }> = [];
const multiToolTask = await runDesktopTask({
  task: {
    ...task,
    taskId: 'task-runner-multi-tool-call-001',
    executionContext: {
      modelProfileIds: ['qiu-general-default'],
      toolIds: ['local-filesystem', 'office-document'],
      knowledgeBindingIds: [],
      attachmentPaths: ['C:\\QiuAI\\input\\customer-notes.txt']
    }
  },
  workspaceId: 'workspace-multi-tool-call',
  modelProfiles,
  tools,
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['local-filesystem', 'office-document'],
  enabledKnowledgeBindingIds: [],
  modelInvoker: async (request) => {
    multiToolModelInvocationCount += 1;

    if (multiToolModelInvocationCount === 1) {
      assert.match(request.messages[1]?.content ?? '', /Attached file text context/);
      assert.match(request.messages[1]?.content ?? '', /Customer note content/);
      return {
        provider: request.profile.providerName,
        modelName: request.profile.modelName,
        content: [
          '```json',
          '{"toolId":"local-filesystem","action":"filesystem.read_text_file","input":{"path":"C:\\\\QiuAI\\\\input\\\\customer-notes.txt"}}',
          '```'
        ].join('\n')
      };
    }

    if (multiToolModelInvocationCount === 2) {
      assert.match(request.messages.at(-1)?.content ?? '', /Customer note content/);
      return {
        provider: request.profile.providerName,
        modelName: request.profile.modelName,
        content:
          'QIUAI_DESKTOP_TOOL_CALL: {"toolId":"office-document","action":"office.write_markdown_document","input":{"title":"Customer Summary","folder":"documents","fileName":"customer-summary","content":"## Summary\\n\\nCustomer note content processed."}}'
      };
    }

    assert.match(request.messages.at(-1)?.content ?? '', /customer-summary.md/);
    return {
      provider: request.profile.providerName,
      modelName: request.profile.modelName,
      content: 'Final result generated after reading input and writing office document.'
    };
  },
  desktopToolInvoker: async (request) => {
    multiToolRequests.push({ toolId: request.toolId, action: request.action });

    if (request.action === 'document.extract_text') {
      assert.equal(request.toolId, 'office-document');
      assert.equal(request.allowedRootPaths?.includes('C:\\QiuAI\\input\\customer-notes.txt'), true);
      return {
        toolId: request.toolId,
        action: request.action,
        ok: true,
        output: {
          path: request.input.path,
          text: 'Customer note content'
        }
      };
    }

    if (request.action === 'filesystem.read_text_file') {
      assert.equal(request.allowedRootPaths?.includes('C:\\QiuAI\\input\\customer-notes.txt'), true);
      return {
        toolId: request.toolId,
        action: request.action,
        ok: true,
        output: {
          path: request.input.path,
          content: 'Customer note content'
        }
      };
    }

    assert.equal(request.action, 'office.write_markdown_document');
    return {
      toolId: request.toolId,
      action: request.action,
      ok: true,
      output: {
        localPath: 'C:\\QiuAI\\workspace\\documents\\customer-summary.md'
      }
    };
  },
  completedAt: '2026-07-20T10:00:13.000Z'
});

assert.equal(multiToolModelInvocationCount, 3);
assert.equal(multiToolTask.task.state, 'completed');
assert.deepEqual(multiToolTask.usedToolIds, ['office-document', 'local-filesystem']);
assert.deepEqual(multiToolRequests, [
  { toolId: 'office-document', action: 'document.extract_text' },
  { toolId: 'local-filesystem', action: 'filesystem.read_text_file' },
  { toolId: 'office-document', action: 'office.write_markdown_document' }
]);
assert.equal(multiToolTask.task.artifacts.length, 2);
assert.equal(multiToolTask.task.artifacts[0]?.localPath, 'C:\\QiuAI\\workspace\\documents\\customer-summary.md');
assert.match(multiToolTask.task.artifacts[1]?.content ?? '', /reading input and writing office document/);
assert.ok(multiToolTask.task.executionLogs.some((log) => log.eventType === 'ATTACHMENT_CONTEXT_EXTRACTED'));

const unconfiguredKnowledge = await runDesktopTask({
  task,
  modelProfiles,
  tools,
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['web-search'],
  enabledKnowledgeBindingIds: ['kb-local-folder'],
  modelInvoker: async (request) => ({
    provider: request.profile.providerName,
    modelName: request.profile.modelName,
    content: 'Generated without configured local knowledge source.'
  }),
  completedAt: '2026-07-20T10:00:15.000Z'
});

assert.equal(unconfiguredKnowledge.task.state, 'completed');
assert.ok(
  unconfiguredKnowledge.task.executionLogs.some((log) => log.eventType === 'KNOWLEDGE_SOURCE_UNCONFIGURED')
);

const unconfigured = await runDesktopTask({
  task,
  modelProfiles: modelProfiles.map((profile) => ({
    ...profile,
    apiBaseUrl: undefined,
    apiKey: undefined
  })),
  tools,
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['web-search'],
  enabledKnowledgeBindingIds: ['kb-local-folder'],
  modelInvoker: async () => {
    throw new Error('should not invoke unconfigured model');
  },
  completedAt: '2026-07-20T10:00:30.000Z'
});

assert.equal(unconfigured.task.state, 'failed');
assert.ok(unconfigured.task.executionLogs.some((log) => log.eventType === 'MODEL_API_CONFIG_MISSING'));
assert.ok(unconfigured.task.executionLogs.some((log) => log.eventType === 'LOCAL_RUN_FAILED'));

const failed = await runDesktopTask({
  task,
  modelProfiles,
  tools,
  enabledModelProfileIds: [],
  enabledToolIds: ['web-search'],
  enabledKnowledgeBindingIds: ['kb-local-folder'],
  modelInvoker: async () => {
    throw new Error('should not invoke disabled model');
  },
  completedAt: '2026-07-20T10:01:00.000Z'
});

assert.equal(failed.task.state, 'failed');
assert.equal(failed.task.artifacts.length, 0);
assert.equal(failed.task.currentRun?.status, 'failed');
assert.ok(failed.task.executionLogs.some((log) => log.eventType === 'LOCAL_RUN_FAILED'));

console.log('Desktop local task runner passed.');
