import assert from 'node:assert/strict';

import type { ModelProfile, ToolManifest } from './desktop-contract.js';
import { runDesktopTask } from './desktop-task-runner.js';
import { createMockTaskDetail } from './workbench-data.js';

const modelProfiles: ModelProfile[] = [
  {
    id: 'qiu-general-default',
    providerId: 'provider-local',
    providerName: 'Local Provider',
    modelName: 'general-chat',
    purpose: 'general',
    apiBaseUrl: 'https://model.example/v1',
    apiKey: 'test-api-key'
  }
];

const tools: ToolManifest[] = [
  {
    id: 'web-search',
    name: 'Web Search',
    version: '1.0.0',
    scope: 'hybrid',
    entryPoint: 'api',
    capabilities: ['web_search'],
    requiresApproval: false
  },
  {
    id: 'office-document',
    name: 'Office Document',
    version: '1.0.0',
    scope: 'desktop',
    entryPoint: 'bridge',
    capabilities: ['document_edit'],
    requiresApproval: true
  },
  {
    id: 'local-filesystem',
    name: 'Local Filesystem',
    version: '1.0.0',
    scope: 'desktop',
    entryPoint: 'native',
    capabilities: ['filesystem'],
    requiresApproval: true
  }
];

const task = createMockTaskDetail({
  taskId: 'task-runner-001',
  roleCode: 'ai-ops',
  roleName: 'AI Ops',
  title: 'Prepare weekly customer follow-up summary',
  input: 'Summarize the customer notes and create next actions.',
  state: 'queued',
  artifactCount: 0,
  costCents: 0,
  executionContext: {
    modelProfileIds: ['qiu-general-default'],
    toolIds: ['web-search', 'office-document'],
    knowledgeBindingIds: ['kb-local-folder']
  }
});

const completed = await runDesktopTask({
  task,
  modelProfiles,
  tools,
  knowledgeSources: [
    {
      id: 'kb-local-folder',
      source: 'local_folder',
      label: 'Customer Docs',
      enabled: true,
      createdAt: '2026-07-20T09:55:00.000Z',
      localPath: 'C:\\QiuAI\\CustomerDocs',
      lastIndexedAt: '2026-07-20T09:56:00.000Z',
      summary: 'Customer renewal notes and follow-up SOP.'
    }
  ],
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['web-search'],
  enabledKnowledgeBindingIds: ['kb-local-folder'],
  modelInvoker: async (request) => {
    assert.equal(request.profile.id, 'qiu-general-default');
    assert.equal(request.messages.length, 2);
    assert.match(request.messages[1]?.content ?? '', /Customer Docs/);
    return {
      provider: request.profile.providerName,
      modelName: request.profile.modelName,
      content: 'Customer follow-up summary generated by model.',
      inputTokens: 300,
      outputTokens: 180
    };
  },
  completedAt: '2026-07-20T10:00:00.000Z'
});

assert.equal(completed.task.state, 'completed');
assert.equal(completed.task.artifacts.length, 1);
assert.match(completed.task.artifacts[0]?.content ?? '', /Customer follow-up summary/);
assert.equal(completed.task.costRecords.length, 1);
assert.equal(completed.task.costRecords[0]?.inputTokens, 300);
assert.deepEqual(completed.usedToolIds, []);
assert.ok(
  completed.task.executionLogs.some((log) => log.eventType === 'TOOL_BINDING_SKIPPED')
);
assert.ok(
  completed.task.executionLogs.some((log) => log.eventType === 'MODEL_RESPONSE_RECEIVED')
);

let toolCallingModelInvocationCount = 0;
const toolCallingTask = await runDesktopTask({
  task: {
    ...task,
    taskId: 'task-runner-tool-call-001',
    executionContext: {
      modelProfileIds: ['qiu-general-default'],
      toolIds: ['local-filesystem'],
      knowledgeBindingIds: []
    }
  },
  workspaceId: 'workspace-tool-call',
  modelProfiles,
  tools,
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['local-filesystem'],
  enabledKnowledgeBindingIds: [],
  modelInvoker: async (request) => {
    toolCallingModelInvocationCount += 1;
    if (toolCallingModelInvocationCount === 1) {
      return {
        provider: request.profile.providerName,
        modelName: request.profile.modelName,
        content:
          'QIUAI_DESKTOP_TOOL_CALL: {"toolId":"local-filesystem","action":"filesystem.write_text_file","input":{"folder":"reports","fileName":"weekly-summary","content":"Generated weekly summary"}}',
        inputTokens: 120,
        outputTokens: 60
      };
    }

    assert.match(request.messages.at(-1)?.content ?? '', /Desktop tool result/);
    return {
      provider: request.profile.providerName,
      modelName: request.profile.modelName,
      content: 'Final result generated after local filesystem tool execution.',
      inputTokens: 160,
      outputTokens: 90
    };
  },
  desktopToolInvoker: async (request) => {
    assert.equal(request.workspaceId, 'workspace-tool-call');
    assert.equal(request.toolId, 'local-filesystem');
    assert.equal(request.action, 'filesystem.write_text_file');
    assert.equal(request.input.fileName, 'weekly-summary');

    return {
      toolId: request.toolId,
      action: request.action,
      ok: true,
      output: {
        localPath: 'C:\\QiuAI\\workspace\\reports\\weekly-summary.md'
      }
    };
  },
  completedAt: '2026-07-20T10:00:10.000Z'
});

assert.equal(toolCallingModelInvocationCount, 2);
assert.equal(toolCallingTask.task.state, 'completed');
assert.deepEqual(toolCallingTask.usedToolIds, ['local-filesystem']);
assert.match(toolCallingTask.task.artifacts[0]?.content ?? '', /after local filesystem tool execution/);
assert.ok(toolCallingTask.task.executionLogs.some((log) => log.eventType === 'TOOL_CALL_DETECTED'));
assert.ok(toolCallingTask.task.executionLogs.some((log) => log.eventType === 'TOOL_INVOKED'));
assert.ok(toolCallingTask.task.executionLogs.some((log) => log.eventType === 'TOOL_RESULT_RETURNED_TO_MODEL'));

const unconfiguredKnowledge = await runDesktopTask({
  task,
  modelProfiles,
  tools,
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['web-search'],
  enabledKnowledgeBindingIds: ['kb-local-folder'],
  modelInvoker: async (request) => ({
    provider: request.profile.providerName,
    modelName: request.profile.modelName,
    content: 'Generated without configured local knowledge source.'
  }),
  completedAt: '2026-07-20T10:00:15.000Z'
});

assert.equal(unconfiguredKnowledge.task.state, 'completed');
assert.ok(
  unconfiguredKnowledge.task.executionLogs.some((log) => log.eventType === 'KNOWLEDGE_SOURCE_UNCONFIGURED')
);

const unconfigured = await runDesktopTask({
  task,
  modelProfiles: modelProfiles.map((profile) => ({
    ...profile,
    apiBaseUrl: undefined,
    apiKey: undefined
  })),
  tools,
  enabledModelProfileIds: ['qiu-general-default'],
  enabledToolIds: ['web-search'],
  enabledKnowledgeBindingIds: ['kb-local-folder'],
  modelInvoker: async () => {
    throw new Error('should not invoke unconfigured model');
  },
  completedAt: '2026-07-20T10:00:30.000Z'
});

assert.equal(unconfigured.task.state, 'failed');
assert.ok(unconfigured.task.executionLogs.some((log) => log.eventType === 'MODEL_API_CONFIG_MISSING'));
assert.ok(unconfigured.task.executionLogs.some((log) => log.eventType === 'LOCAL_RUN_FAILED'));

const failed = await runDesktopTask({
  task,
  modelProfiles,
  tools,
  enabledModelProfileIds: [],
  enabledToolIds: ['web-search'],
  enabledKnowledgeBindingIds: ['kb-local-folder'],
  modelInvoker: async () => {
    throw new Error('should not invoke disabled model');
  },
  completedAt: '2026-07-20T10:01:00.000Z'
});

assert.equal(failed.task.state, 'failed');
assert.equal(failed.task.artifacts.length, 0);
assert.equal(failed.task.currentRun?.status, 'failed');
assert.ok(failed.task.executionLogs.some((log) => log.eventType === 'LOCAL_RUN_FAILED'));

console.log('Desktop local task runner passed.');
